[project]
name = "graphty"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lukas Plank", email = "lupl@tuta.io" }
]
requires-python = ">=3.12"
dependencies = [
    "polars>=1.39.3",
    "pydantic>=2.12.5",
]

[build-system]
requires = ["uv_build>=0.9.30,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pytest-randomly>=4.1.0",
    "ruff>=0.15.17",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
